[package]
name = "stfrs"
description = "Stream Filter in Rust."
version = "0.1.0"
edition = "2021"
authors = ["Akihiro Shoji"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.0.2"
colored = "2.0.0"
